Doenet/DoenetML

packages/doenetml/src/Viewer/PageViewer.jsx

Apply relevant portion of Doenet/DoenetTools#2322

always use core renderer state for unrendered pages

---

packages/doenetml/src/Viewer/ActivityViewer.jsx

load page doenetML if loading old saved state

---

packages/doenetml/src/Core/Core.js
packages/test-cypress/cypress/e2e/tagSpecific/updatevalue.cy.js

protect against undefined component

trigger chained actions on unnamed shadows

---

packages/doenetml-worker/src/components/Graph.js
packages/doenetml/src/Viewer/renderers/graph.jsx

Port of Doenet/DoenetTools#2353
Closes #36

optimistic ui for graph bounds

---

packages/doenetml-worker/src/components/Point.js
packages/test-cypress/cypress/e2e/tagSpecific/point2.cy.js

Port of Doenet/DoenetTools#2362

force numericalXs of point to be numerical

---

packages/doenetml-worker/src/utils/math.ts
packages/test-cypress/cypress/e2e/tagSpecific/mathinput.cy.js

Port of Doenet/DoenetTools#2363

convert unicode prime to apostrophe in latex

---

packages/doenetml-worker/src/components/SolveEquations.js
packages/test-cypress/cypress/e2e/tagSpecific/solveequations.cy.js

Port of Doenet/DoenetTools#2364

solveequations handles invalid equation

---

packages/doenetml-worker/src/components/Paginator.js
packages/doenetml/src/Viewer/renderers/paginatorControls.jsx
packages/test-cypress/cypress/e2e/tagSpecific/paginator.cy.js

Port of Doenet/DoenetTools#2365

paginatorControls ignore read-only flag

---

packages/doenetml-worker/src/Core.js
packages/doenetml-worker/src/CoreWorker.js
packages/doenetml-worker/src/components/Answer.js
packages/doenetml-worker/src/components/Document.js
packages/doenetml-worker/src/utils/expandDoenetML.js
packages/doenetml/src/Viewer/ActivityViewer.jsx

Port of Doenet/DoenetTools#2366

Finish assessment warning

---

.github/workflows/on-pull-request.yml
package-lock.json
package.json
packages/doenetml-prototype/package.json
packages/doenetml-prototype/src/DoenetML.tsx
packages/doenetml-prototype/tsconfig.json
packages/doenetml-prototype/vite.config.ts
packages/doenetml-worker-rust/package.json
packages/test-viewer/src/test/testViewer.tsx
packages/test-viewer/tsconfig.json
packages/ui-components/package.json
packages/utils/package.json
packages/virtual-keyboard/package.json

This PR uses `npm` to install `wasm-pack` and skips absent tests so that CI succeeds.

Fix tests and build

---

packages/parser/src/dast-to-xml/utils.ts
packages/parser/test/dast-advanced.test.ts
packages/parser/test/dast-basic.test.ts
packages/parser/test/filter-position.test.ts

The previous `filterPositionInfo` didn't recuse properly. This new one should :-)

Correctly trim position info

---

packages/doenetml-worker-rust/lib-doenetml-core/Cargo.toml
packages/doenetml-worker-rust/lib-doenetml-core/benches/core_benchmark.rs
packages/doenetml-worker-rust/lib-doenetml-core/benches/samples/reverse_thousand_chain.doenet
packages/doenetml-worker-rust/lib-doenetml-core/benches/samples/thousand_chain.doenet
packages/doenetml-worker-rust/lib-doenetml-core/benches/samples/thousand_chain_flipped.doenet
packages/doenetml-worker-rust/lib-doenetml-core/benches/samples/thousand_star.doenet
packages/doenetml-worker-rust/lib-doenetml-core/tests/test_utils/mod.rs

This PR adds benchmarking to the Rust code for old_core.

Add benchmarks

---

packages/test-cypress/cypress/e2e/tagSpecific/functionoperators.cy.js
packages/utils/src/components/function.js

fix bug in derivative of invalid interpolated function

---

packages/doenetml-worker/src/components/Text.js
packages/test-cypress/cypress/e2e/tagSpecific/text.cy.js

This PR adds a  `numCharacters` property on `<text>` components, which gives the number of characters in the text string.

numCharacters property of text component

---

package-lock.json
packages/doenetml/package.json
packages/test-cypress/cypress/e2e/tagSpecific/math.cy.js

This PR adds support for some logical operations inside a `<math>`: neg, implies, impliedby, iff, rightarrow, leftarrow, leftrightarrow.

add more logical operators

---

package-lock.json
packages/doenetml-worker/src/Core.js
packages/doenetml-worker/src/components/Answer.js
packages/doenetml-worker/src/components/abstract/BaseComponent.js
packages/doenetml/package.json
packages/doenetml/src/Viewer/PageViewer.jsx
packages/doenetml/src/index.js

This PR adds support for sending events via the SPLICE protocol.
It also numbers answers that are present in the raw DoenetML and sends those numbers with the submitted events.

send events via SPLICE protocol

---

package-lock.json
packages/doenetml/package.json
packages/doenetml/src/Viewer/ActivityViewer.jsx
packages/doenetml/src/Viewer/PageViewer.jsx
packages/doenetml/src/Viewer/renderers/answer.jsx
packages/doenetml/src/Viewer/renderers/booleanInput.jsx
packages/doenetml/src/Viewer/renderers/choiceInput.jsx
packages/doenetml/src/Viewer/renderers/mathInput.jsx
packages/doenetml/src/Viewer/renderers/matrixInput.jsx
packages/doenetml/src/Viewer/renderers/textInput.jsx
packages/doenetml/src/doenetml.jsx

This PR adds the `ShowAnswerTitle` prop to the `<DoenetML>` component, which, if true, displays the name of the answer on hover (i.e., as a button title). It also improves the display of disabled check work buttons.

Answer tweaks

---

package-lock.json
packages/doenetml-worker/src/components/SubsetOfReals.js
packages/doenetml-worker/src/components/SubsetOfRealsInput.js
packages/doenetml/package.json
packages/doenetml/src/Viewer/renderers/subsetOfRealsInput.jsx
packages/static-assets/src/generated/doenet-schema.json
packages/test-cypress/cypress/e2e/tagSpecific/subsetofreals.cy.js
packages/utils/src/math/subset-of-reals.js

This PR adds the properties `points`, `pointsClosed`, `intervals`, and `isolatedPoints` to both `<subsetOfReals>` and `<subsetOfRealsInput>`.

add interval and point properties to subsetOfReals

---

.github/workflows/on-pull-request.yml
.prettierignore
.prettierignoreci
package-lock.json
packages/doenetml-worker/src/Core.js
packages/doenetml-worker/src/components/Copy.js
packages/doenetml-worker/src/components/Group.js
packages/doenetml-worker/src/components/Map.js
packages/doenetml-worker/src/components/abstract/BaseComponent.js
packages/doenetml-worker/src/utils/constraints.js
packages/doenetml-worker/src/utils/copy.js
packages/test-cypress/cypress.config.js
packages/test-cypress/cypress/e2e/copying/unlinked.cy.js
packages/test-cypress/cypress/e2e/errorsAndWarnings/errors.cy.js
packages/test-cypress/cypress/e2e/tagSpecific/copy.cy.js
packages/test-cypress/cypress/e2e/tagSpecific/copy2.cy.js
packages/test-cypress/multi-reporter-config.json

This PR fixes the behavior of unlinked copies of groups and maps. With these changes, one can use an unlinked copy to take a snapshot of groups and maps, and the snapshots will match the state at the moment it was taken.

improve behavior of unlinked copies

---

package-lock.json
packages/doenetml-iframe/package.json
packages/doenetml-iframe/src/index.tsx
packages/doenetml/package.json
packages/standalone/package.json

Fixes flaw where doenetml-iframe added the virtual keyboard regardless of the value of the addVirtualKeyboard prop

doenetml-iframe hides virtual keyboard if addVirtualKeyboard prop is false

---

packages/doenetml-prototype/src/renderers/doenet/graph.tsx
packages/doenetml-prototype/src/utils/array.ts
packages/doenetml-worker-rust/lib-doenetml-core/src/components/doenet/graph.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/components/traits/component_on_action.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/core/document_model/dependency_creation_helpers/data_query_pick_prop.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/core/props/prop.rs
packages/doenetml-worker-rust/lib-doenetml-core/tests/by_component/graph.rs
packages/doenetml-worker-rust/lib-doenetml-core/tests/by_component/mod.rs

This PR adds attributes and props on `<graph>` to control and read out the limits of the axes.

graph axis limit attributes

---

packages/docs-nextra/components/iframe-doenetml.tsx
packages/docs-nextra/package.json
packages/docs-nextra/pages/reference/_meta.ts
packages/docs-nextra/pages/tutorials/introdTutorial/iT1-9-sliders.mdx
packages/docs-nextra/pages/tutorials/quickStart.mdx
packages/docs-nextra/tsconfig.json
packages/doenetml-iframe/vite.config-iframe-editor.ts
packages/doenetml-iframe/vite.config-iframe-viewer.ts
packages/virtual-keyboard/src/virtual-keyboard/keyboard-tray.tsx
packages/virtual-keyboard/src/virtual-keyboard/unique-keyboard-tray.tsx

Adds a fallback for the virtual keyboard to detect if `window` is undefined.

Fix `window undefined` issue

---

packages/lsp-tools/test/doenet-auto-complete.test.ts

This PR demonstrates a regression in the auto-completion algorithm.

test demonstrating autocomplete regression

---

packages/doenetml-worker/src/utils/math.ts

In math inverse definition, address lists of vectors with empty components

---

package-lock.json
package.json
packages/doenetml-iframe/package.json
packages/doenetml-worker/src/test/tagSpecific/boolean.test.ts
packages/doenetml/package.json
packages/standalone/package.json

upgrade math-expressions
bump version

Fix bug in comparing negative numbers with symbolic equality

---

package-lock.json
packages/doenetml-iframe/package.json
packages/doenetml-worker/src/components/Vector.js
packages/doenetml/package.json
packages/doenetml/src/Viewer/renderers/answer.jsx
packages/doenetml/src/Viewer/renderers/booleanInput.jsx
packages/doenetml/src/Viewer/renderers/choiceInput.jsx
packages/doenetml/src/Viewer/renderers/mathInput.jsx
packages/doenetml/src/Viewer/renderers/matrixInput.jsx
packages/doenetml/src/Viewer/renderers/textInput.jsx
packages/standalone/package.json

This PR fixes a flaw where pressing enter on check-work buttons was submitting the response twice.

don't double-submit when pressing enter on submit buttons

---

packages/docs-nextra/pages/reference/doenetML_components/Sample_Component.mdx
packages/docs-nextra/pages/reference/doenetML_components/_meta.ts
packages/docs-nextra/pages/reference/doenetML_components/alert.mdx
packages/docs-nextra/pages/reference/doenetML_components/angle.mdx
packages/docs-nextra/pages/reference/doenetML_components/componentIndex.mdx
packages/docs-nextra/pages/tutorials/_meta.ts

This PR tests the new format for documentation

updated angle and hid quickstart

---

packages/docs-nextra/pages/reference/doenetML_components/_meta.ts
packages/docs-nextra/pages/reference/doenetML_components/abs.mdx
packages/docs-nextra/pages/reference/doenetML_components/alert.mdx
packages/docs-nextra/pages/reference/doenetML_components/angle.mdx
packages/docs-nextra/pages/reference/doenetML_components/componentIndex.mdx
packages/docs-nextra/pages/reference/doenetML_components/math.mdx
packages/docs-nextra/pages/reference/doenetML_components/point.mdx

added math to docs

---

package-lock.json
packages/doenetml-iframe/package.json
packages/doenetml/package.json
packages/doenetml/src/Viewer/renderers/embed.jsx
packages/doenetml/src/Viewer/renderers/graph.jsx
packages/doenetml/src/Viewer/renderers/legend.jsx
packages/standalone/package.json
packages/test-cypress/cypress/e2e/tagSpecific/legend.cy.js

This PR fixes a bug where legacy MathJax functions were called to wait for it to finish processing.
It also removes the arrow navigation buttons from the graph given that dragging now moves the graph.

fix bug when calling MathJax function

---

packages/doenetml/src/Viewer/DocViewer.tsx

The PR fixed a bug where, if callbacks from Core were processed in a different order in the viewer, any children of the document would fail to render. This bug was triggered consistently in Firefox, preventing documents from rendering in Firefox.

Fix bug that was preventing document from rendering in Firefox

---

.github/ISSUE_TEMPLATE/bug_report.yml

Added a Github form people can use to report issues.

Github bug report template

---

packages/parser/src/macros/macros.peggy
packages/parser/test/macro-parse.test.ts

Don't parse $5 as a macro

---

packages/parser/src/dast-to-xml/utils.ts
packages/parser/src/lezer-to-dast/gobble-function-arguments.ts
packages/parser/src/lezer-to-dast/lezer-to-dast-utils.ts
packages/parser/src/lezer-to-dast/lezer-to-dast-v6.ts
packages/parser/src/lezer-to-dast/lezer-to-dast.ts
packages/parser/test/dast-advanced.test.ts

Fix position information in macros and function macros

---

.github/workflows/on-pull-request.yml
package-lock.json
package.json
packages/doenetml-prototype/package.json
packages/doenetml-prototype/vite.config.ts
packages/doenetml-worker-javascript/package.json
packages/doenetml-worker-javascript/src/CoreWorker.ts
packages/doenetml/package.json
packages/doenetml/src/EditorViewer/EditorViewer.tsx
packages/doenetml/src/EditorViewer/editor-viewer.css
packages/doenetml/tsconfig.json
packages/parser/package.json
packages/parser/src/v06-to-v07/core-info/core.ts
packages/parser/test/v06-to-v07-upgrade.test.ts
packages/parser/tsconfig.json
packages/parser/vite.config.ts
packages/parser/vite.config.v06-to-v07.ts

This PR allows the upgrade script to run in the browser.

Add Upgrade Syntax Button for v06 to v07

---

package-lock.json
packages/doenetml-iframe/package.json
packages/doenetml-worker-javascript/src/test/errorsAndWarnings/errors.test.ts
packages/doenetml/package.json
packages/parser/src/dast-normalize/enforce-valid-names.ts
packages/parser/test/normalize-dast.test.ts
packages/standalone/package.json

This PR updates the error handling for invalid component names and invalid name attributes.
Resolves #482
Resolves #485

errors for invalid names

---

package-lock.json
packages/doenetml-iframe/package.json
packages/doenetml/package.json
packages/standalone/package.json
packages/standalone/vite.config.ts

Fix problem where the style of standalone wasn't bundled correctly.

fix build of standalone package

---

packages/doenetml-worker-rust/Cargo.toml
packages/doenetml-worker-rust/lib-doenetml-core/Cargo.toml
packages/doenetml-worker-rust/lib-doenetml-core/src/dast/ref_resolve/build_resolver.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/dast/ref_resolve/build_resolver.test.rs
packages/doenetml-worker-rust/lib-js-wasm-binding/Cargo.toml
packages/doenetml-worker-rust/lib-rust-macros/Cargo.toml

This PR improves the speed of adding and deleting elements to/from the resolver. It removes the use of a regular expression to parse attribute names and removes unnecessary collections of iterators into vectors.

improve resolver speed

---

packages/doenetml-worker-javascript/src/Core.js
packages/doenetml-worker-javascript/src/test/tagSpecific/functionTag.test.ts
packages/doenetml-worker-javascript/src/utils/copy.js

This PR fixes a couple bugs with `<function>`s in some edge cases involving `<conditionalContent>`.

bug fixes involving functions

---

package-lock.json
packages/doenetml-iframe/package.json
packages/doenetml-iframe/src/utils.ts
packages/doenetml-worker-javascript/src/Core.js
packages/doenetml-worker-javascript/src/components/Answer.js
packages/doenetml-worker-javascript/src/components/Pretzel.js
packages/doenetml-worker-javascript/src/components/abstract/BaseComponent.js
packages/doenetml/package.json
packages/doenetml/src/EditorViewer/EditorViewer.tsx
packages/doenetml/src/Viewer/DocViewer.tsx
packages/doenetml/src/Viewer/renderers/answer.tsx
packages/doenetml/src/Viewer/renderers/pretzel.tsx
packages/standalone/package.json
packages/static-assets/src/generated/doenet-relaxng-schema.json
packages/static-assets/src/generated/doenet-schema.json
packages/v06-to-v07/package.json

It updates the answer response menu to use root names to identify answers and fixes some bugs.

fix answer data and response bugs

---

packages/doenetml-worker-rust/lib-doenetml-core/src/core/document_model/document_model.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/core/state/types/component_refs.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/core/state/types/content_refs.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/dast/dast_structure.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/dast/flat_dast/parent_iterator.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/dast/ref_resolve/node_traversal.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/graph/directed_graph/graph_walk.rs
packages/doenetml-worker-rust/lib-doenetml-core/src/graph/directed_graph/iterators.rs
packages/doenetml-worker-rust/lib-rust-macros/src/component_module/utils/doc_comments.rs
packages/doenetml-worker-rust/lib-rust-macros/src/test_data_query_types/test_data_query_types.rs

This PR simply adjusts rust code to comply with  new lint rules in rust 1.89.

address new rust lint rules

---

packages/v06-to-v07/src/index.ts
packages/v06-to-v07/src/normalize-capitalization.ts
packages/v06-to-v07/src/reparse-attribute.ts
packages/v06-to-v07/test/v06-to-v07-upgrade.test.ts

This PR adds some more cases that the update script can convert.

Improve v06 to v07 upgrade script

---

packages/doenetml/src/Viewer/renderers/slider.tsx

This PR fixes a bug in the slider renderer where a possible exception was not being caught.

catch error in slider renderer

---

packages/static-assets/src/generated/doenet-relaxng-schema.json
packages/static-assets/src/generated/doenet-schema.json

This PR builds the schema to add the `description` attribute of #613.

build schema

---

packages/test-cypress/cypress/e2e/tagSpecific/answer.cy.js
packages/test-cypress/cypress/e2e/variants/specifysinglevariant.cy.js

This PR fix two cypress tests to account for changed desired behavior.

fix two cypress tests
