Doenet/DoenetML

packages/doenetml/src/Core/Core.js, packages/test-cypress/cypress/e2e/errorsAndWarnings/warnings.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/selectrandomnumbers.cy.js
Fixed by correctly updating composites in response to unmatched children inside attributes
=> Update attribute warning even if hidden

packages/doenetml-worker/src/components/DiscreteSimulationResultPolyline.js
Resolves #40
Port of Doenet/DoenetTools#2357
=> add missing actions to discreteSimulationResultPolyline

packages/doenetml-worker/src/Core.js, packages/doenetml/src/DoenetML.jsx, packages/doenetml/src/Viewer/ActivityViewer.jsx
Port of Doenet/DoenetTools#2370
=> Wait to avoid overlapping state saves

.github/workflows/on-pull-request.yml, .gitignore, README.md, package-lock.json, package.json, packages/codemirror/package.json, packages/doenetml-worker/package.json, packages/doenetml/package.json, packages/lsp-tools/package.json, packages/lsp/package.json, packages/parser/package.json, packages/standalone/package.json, packages/static-assets/package.json, packages/test-viewer/package.json, packages/ui-components/package.json, packages/utils/package.json, packages/virtual-keyboard/package.json, scripts/ensure-consistency.ts
[wireit](https://github.com/google/wireit) is a script that handles dependency building and caching, configured in `package.json`. This PR changes the build processes for most packages to use `wireit`.
Results:
* building should be much faster since building of deps can happen in parallel
* You can now run `npm run build --watch` in a workspace and it will automatically rebuild all deps when a file changes (no need for multiple watched directories)
The top-level `npm run build` was changed to only build `test-viewer`, which skips the building of `test-cypress` and `standalone`. This should speed things up for most devs. The CI should still build all of the packages.
=> Use wireit to auto-build dependencies

packages/doenetml/src/Viewer/renderers/booleanInput.css, packages/doenetml/src/Viewer/renderers/booleanInput.jsx
The old rule of "hide anything of type input that is anywhere below an an element with a class name of `container`" was causing issues in Runestone and making all of the form inputs disappear.
I am also working on a fancier way to hide all of our CSS below a given root container div when embedded in another site, but that seems easiest to accomplish by introducing a CSS preprocessor like less or SASS. The overly general nature of this CSS rule seemed like something worth cleaning up for our own sake inside of the project.
=> Make CSS selectors for the customized checkbox in booleanInput more selective

.vscode/doenet.code-workspace, README.md
This PR adds a `.vscode/doenet.code-workspace` file. Clicking that file and then `Open Workspace`, or invoking
```
code .vscode/doenet.code-workspace
```
directly will open a multi-root vscode workspace where rust-analyzer is configured correctly.
=> Make Rust Development Easier

packages/doenetml-worker-rust/lib-doenetml-core/src/components/component.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/component_enum.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/doenet/mod.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/doenet/xref.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/special/_ref.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/special/mod.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/traits/component_attributes.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/component_builder.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/document_model/debug/mermaid.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/general_prop/component_ref_prop.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/general_prop/independent_prop.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/props/prop_profile.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast.rs, packages/doenetml-worker-rust/lib-doenetml-core/tests/by_component/mod.rs, packages/doenetml-worker-rust/lib-doenetml-core/tests/by_component/xref.rs, packages/doenetml-worker-rust/lib-doenetml-core/tests/test_utils/mod.rs, packages/doenetml-worker-rust/lib-rust-macros/src/component_module/generate_component_module.test.rs, packages/doenetml-worker-rust/lib-rust-macros/src/component_module/items/attributes.rs, packages/doenetml-worker-rust/lib-rust-macros/src/component_module/items/component.rs, packages/doenetml-worker-rust/lib-rust-macros/src/lib.rs
Attributes can now be annotated with `preserve_refs`. If so, any `$foo` refs that appear in the specified attribute will not be expanded to clones of their referent. Instead, they will be converted to special `_ref` components which hold the `idx` of their referent.
=> Add a `preserve_refs` annotation for attributes

packages/doenetml-worker-rust/lib-doenetml-core/src/core/props/prop_profile.rs, packages/doenetml-worker-rust/lib-rust-macros/src/component_module/items/props.rs
Add compile-time checks to make sure PropProfile and PropValueType agree.
=> Add compile-time checks to make sure PropProfile and PropValueType agree

packages/doenetml-prototype/src/state/redux-slices/dast/utils/convert-pretext-attributes.ts, packages/doenetml-prototype/src/state/redux-slices/dast/utils/normalize-dast.ts, packages/doenetml-prototype/test/normalize-dast.test.ts, packages/parser/src/macros/types.ts
PreTeXt uses `xml:id` instead of `name`, and allows for xrefs of the form `<xref ref="ref" />`. This PR changes `xml:id` to `name` before processing. It also converts `<xref ref="ref" />` to `<xref ref="$ref" />`
=> Normalize xml:id and ref attributes to be doenet compatible

packages/doenetml-worker/src/ComponentTypes.js, packages/doenetml-worker/src/components/RegionBetweenCurves.js, packages/doenetml/src/Viewer/renderers/regionBetweenCurves.jsx, packages/static-assets/src/generated/doenet-schema.json, packages/test-cypress/cypress/e2e/tagSpecific/regionBetweenCurves.cy.js
This PR creates a new DoenetML component `<regionBetweenCurves>` that displays the region between two functions, optionally flipping the functions across "x=y" before displaying the region.
=> regionBetweenCurves component

packages/doenetml-worker/src/ComponentTypes.js, packages/doenetml-worker/src/components/Polyline.js, packages/static-assets/src/generated/doenet-schema.json, packages/test-cypress/cypress/e2e/tagSpecific/polygon.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/triangle.cy.js
This PR temporarily removes the `<vertexConstraints>`, `<edgeConstraints>`, and `<attractSegmentTo>` components until we can dedicate time to fix and revive them.
The main use case for these components was superseded by the `<stickyGroup>` component. However, these components could give authors more control over how vertices and edges are constrained.
=> temporarily remove vertexConstraints and edgeConstraints components

packages/doenetml-worker/src/Core.js, packages/parser/src/parser.ts, packages/test-cypress/cypress/e2e/tagSpecific/answer.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/codeeditor.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/selectrandomnumbers.cy.js
With this PR, the doenetml parser converts html entities and the like into strings and merges consecutive strings.
With this change, cypress tests are finally passing again.
=> Parser turns html entities to strings

packages/doenetml/package.json, packages/doenetml/src/DoenetML.css, packages/doenetml/vite.config.ts, packages/standalone/package.json, packages/standalone/vite.config.ts
With this PR, building the `doenetml` and `standalone` packages  creates pared-down `package.json` files in the dist directory. A new `npm run publish` script in each packge publishes to npm from the dist directories using those `package.json` files.
The PR also changes how fonts were included in `doenetml` so that they can be found by the `standalone` package.
=> tweak packaging and fix font issue

package-lock.json, packages/doenetml-iframe/README.md, packages/doenetml-iframe/index.html, packages/doenetml-iframe/package.json, packages/doenetml-iframe/src/iframe-index.ts, packages/doenetml-iframe/src/index.tsx, packages/doenetml-iframe/src/resize-watcher.ts, packages/doenetml-iframe/src/test-main.tsx, packages/doenetml-iframe/tsconfig.json, packages/doenetml-iframe/vite.config-iframe.ts, packages/doenetml-iframe/vite.config.ts, packages/doenetml/package.json, packages/doenetml/vite.config.ts, packages/standalone/package.json, packages/standalone/vite.config.ts, scripts/transform-package-json.ts
This PR creates a `DoenetMLIframe` component. When using this component, you specify a copy of `standalone` to use (e.g., from a CDN URL). Its contents are completely isolated inside of an iframe. This means, using `DoementMLIframe`, you can run multiple versions of DoenetML at the same time on the same page.
One drawback of this approach is that you cannot directly pass the React component the usual callbacks. Instead, you have to use the provided `onMessage(...)` prop to receive messages coming from the `<DoenetML ... />` component that is rendered in the iframe.
=> Make a DoenetMLIframe component

packages/doenetml-worker/src/utils/extrema.js
Recent improvements to `math-expressions` updated how subsets of reals are encoded. This PR fixes a regression introduced by those changes.
=> fix regression from recent math-expression changes

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-iframe/src/iframe-editor-index.ts, packages/doenetml-iframe/src/iframe-viewer-index.ts, packages/doenetml-iframe/src/index.tsx, packages/doenetml-iframe/src/test-main.tsx, packages/doenetml-iframe/src/utils.ts, packages/doenetml-iframe/vite.config.ts, packages/doenetml/package.json, packages/doenetml/src/Viewer/ActivityViewer.tsx, packages/doenetml/src/Viewer/renderers/graph.jsx, packages/doenetml/src/Viewer/renderers/mathInput.jsx, packages/doenetml/src/doenetml.tsx, packages/doenetml/tsconfig.json, packages/doenetml/vite.config.ts, packages/standalone/package.json, packages/standalone/tsconfig.json, packages/standalone/vite.config.ts, packages/test-cypress/tsconfig.json, packages/test-viewer/tsconfig.json, packages/virtual-keyboard/src/virtual-keyboard/external-virtual-keyboard.tsx, packages/virtual-keyboard/src/virtual-keyboard/index.ts, packages/virtual-keyboard/src/virtual-keyboard/keys.ts, packages/virtual-keyboard/src/virtual-keyboard/outside-iframe-keyboard.tsx, packages/virtual-keyboard/src/virtual-keyboard/recoil-virtual-keyboard.tsx, packages/virtual-keyboard/src/virtual-keyboard/unique-keyboard-tray.tsx, packages/virtual-keyboard/vite.config.ts
This PR moves the virtual keyboard outside the iframe if DoenetViewer or DoenetEditor are access via `doenetml-iframe`. This allows the keyboard to placed at the bottom of the browser window regardless of the size of the iframe.
=> Move virtual keyboard outside iframe

packages/doenetml-worker-rust/lib-doenetml-core/src/components/component_enum.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/doenet/graph.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/components/doenet/mod.rs
This PR adds a `<graph>` component to the 0.9 rust worker.
=> create a graph component

packages/doenetml-worker-rust/lib-doenetml-core/src/core/core.test.browser.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/general_prop/math_prop.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/math_via_wasm.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/core/state/types/math_expr.rs, packages/doenetml-worker-rust/lib-js-wasm-binding/src/eval-math.ts, packages/doenetml-worker-rust/lib-js-wasm-binding/src/index.ts
This PR fixes the serialization of `MathExpr` in rust so that it matches the TypeScript type, fixes a regression, and adds regression tests. It also adds conversion functions between `MathExpr` and numbers.
=> Math expression refinements and tests

packages/doenetml-worker/src/components/abstract/BaseComponent.js, packages/doenetml/src/Viewer/renderers/answer.jsx, packages/doenetml/src/Viewer/renderers/booleanInput.jsx, packages/doenetml/src/Viewer/renderers/choiceInput.jsx, packages/doenetml/src/Viewer/renderers/mathInput.jsx, packages/doenetml/src/Viewer/renderers/matrixInput.jsx, packages/doenetml/src/Viewer/renderers/section.jsx, packages/doenetml/src/Viewer/renderers/textInput.jsx
This PR makes sure that all variations of check work buttons and answer status buttons are not tab stops when disabled.
It also updates the section-wide check work button to current styling.
Fixes #221
=> check work buttons are not tab stops when disabled

packages/docs-nextra/next.config.mjs
Since we will use the domain `docs.doenet.org`  rather than `doenet.github.io/DoenetML` for the docs, we no longer want to include `/DoenetML/` in the path for Nextra links.
=> Nextra path does not include github repository name

packages/doenetml-worker/src/Core.js, packages/doenetml/src/Viewer/PageViewer.jsx
This PR adds the feature where if the `postMessages` parameter is set, then a `SPLICE.recordSolutionViewed` is posted to `window` giving information about which solution was viewed.
=> send a SPLICE.recordSolutionViewed message when solution is viewed

packages/virtual-keyboard/src/virtual-keyboard/keyboard-tray.css, packages/virtual-keyboard/src/virtual-keyboard/keyboard-tray.tsx
This PR makes the open keyboard button be white with a black border to make it more visible, especially when it is in front of a dark background.
=> Make open keyboard button more visible

packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/utils/math.ts, packages/doenetml/src/Viewer/PageViewer.jsx
State variable changes to the core web worker were sent a Javascript object. However, in the transition to the web worker, the subset class information was lost. To preserve subset class information, serialize the state changes before passing to the web worker.
=> Fix flaw in passing state variable changes to core

packages/doenetml-worker/src/components/Row.js
Needed so that the sugar of a `<row>` inside a `<matrix>` works properly.
=> Do not remove blank string children on <row> before sugar

packages/doenetml-worker/src/Core.js, packages/doenetml/src/Viewer/PageViewer.jsx, packages/test-cypress/cypress/e2e/tagSpecific/subsetofrealsinput.cy.js, packages/utils/src/index.ts
This PR serializes core state before saving it to indexed db so that Subset class instances are preserved.
It also addes a data_format_version entry to the indexed db entry so that it only loads data saved with the current format.
=> update format for page state saved in indexed db

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/CoreWorker.js, packages/doenetml-worker/src/components/Answer.js, packages/doenetml-worker/src/test/tagSpecific/answer.test.ts, packages/doenetml/package.json, packages/standalone/package.json
This PR creates a warning if one writes an answer such as
```
<answer name="ans">
<mathInput />
<award><when>$ans</when></award>
</answer>
```
where the award depends on the answer's submitted response.
Creating such an answer is an easy mistake when learning DoenetML, but it leads to requiring that one submits an answer twice before it is properly validated.
=> give warning when an answer's award depends on its submitted response

packages/doenetml-worker/src/components/CallAction.js, packages/doenetml-worker/src/components/TriggerSet.js, packages/doenetml-worker/src/components/UpdateValue.js, packages/doenetml-worker/src/test/tagSpecific/callAction.test.ts, packages/doenetml-worker/src/test/tagSpecific/mathinput.test.ts, packages/doenetml-worker/src/test/tagSpecific/selectsamplerandomnumbers.test.ts, packages/doenetml-worker/src/test/tagSpecific/triggerset.test.ts, packages/doenetml-worker/src/test/tagSpecific/updatevalue.test.ts, packages/doenetml/src/DoenetML.css, packages/doenetml/src/Viewer/renderers/button.jsx, packages/ui-components/package.json, packages/ui-components/src/uiComponents/Button.jsx
This PR colors the background of `<callAction>`, `<updateValue>`, and `<triggerSet>` buttons based on the `fillColor` attribute of a style definition. When the mouse hovers over the button, the background changes to a lighter version of the specified color.
Resolves #247.
=> fill color of buttons is styled via style definitions

packages/doenetml-worker/src/components/BooleanList.js, packages/doenetml-worker/src/components/MathList.js, packages/doenetml-worker/src/components/MathOperators.js, packages/doenetml-worker/src/components/NumberList.js, packages/doenetml-worker/src/components/TextList.js, packages/doenetml-worker/src/test/tagSpecific/mathoperators.test.ts, packages/doenetml-worker/src/test/tagSpecific/selectsamplerandomnumbers.test.ts, packages/static-assets/scripts/get-schema.ts, packages/static-assets/src/generated/doenet-relaxng-schema.json, packages/static-assets/src/generated/doenet-schema.json
The PR adds a least common multiple `<lcm>` component that calculates the lcm for numbers and returns a symbolic expression otherwise.
Resolves #250.
=> add lcm math operator

packages/doenetml-worker/src/components/Circle.js, packages/doenetml-worker/src/test/tagSpecific/circle.test.ts
Circle component checks whether it has at least one through point before adding radius as a dependency of center and numericalCenter.
=> Circle center does not depend on radius with zero through points

packages/doenetml-worker/src/components/BooleanInput.js, packages/doenetml-worker/src/components/CallAction.js, packages/doenetml-worker/src/components/ChoiceInput.js, packages/doenetml-worker/src/components/Copy.js, packages/doenetml-worker/src/components/Function.js, packages/doenetml-worker/src/components/MathInput.js, packages/doenetml-worker/src/components/Slider.js, packages/doenetml-worker/src/components/TextInput.js, packages/doenetml-worker/src/components/TriggerSet.js, packages/doenetml-worker/src/components/UpdateValue.js, packages/doenetml-worker/src/components/abstract/BaseComponent.js, packages/doenetml-worker/src/components/abstract/GraphicalComponent.js, packages/doenetml-worker/src/test/graphical/labels.test.ts, packages/doenetml-worker/src/utils/label.js
This PR makes a couple minor adjustments to how the `labelIsName` attribute  functions.
1. The `labelIsName` attribute is not copied when referencing with link=false. Now, the original name is preserved, consistent with the normal behavior with references that link.
2. Labels generated with `labelIsName` no longer use auto-generated names such as "_point1".  This change is in anticipation of phasing out the auto-generated names.
=> LabelIsName tweaks

packages/doenetml-worker/src/components/Label.js, packages/doenetml-worker/src/components/MMeMen.js, packages/doenetml-worker/src/test/tagSpecific/label.test.ts, packages/doenetml-worker/src/utils/math.ts
This PR improves the `value`/`text`/`latex` state variables of `<label>`. In particular,  the `text` state variable no longer matches the `latex` state variable when the label contains math, but instead match the behavior of `text` state variable of other mathematical components.
In addition, the PR has bug fixes for the inverse update functions of these state variables and the  `superSubscriptsToUnicode` function.
=> improvements to label state variables and update functions

packages/doenetml-worker/src/Dependencies.js, packages/doenetml-worker/src/test/graphical/labels.test.ts
This PR fixes a bug where references of points of labeled lines inherit the label.
=> bug fix: references of props do not shadow label

packages/doenetml-worker/src/components/FunctionOperators.js, packages/doenetml-worker/src/test/tagSpecific/functionoperators.test.ts
This PR normalizes applied functions before taking the derivative so that the `<derivative>` tag works with trigonometric functions using the shorthand power notation, such as `sin^2(x)`.
Fixes #219
=> Correctly differentiate trig functions with power notation

package-lock.json, package.json, packages/doenetml-worker/src/test/math/mathExpressionsEquality.test.ts, packages/doenetml-worker/src/test/tagSpecific/math.test.ts, packages/doenetml-worker/src/utils/checkEquality.js
This PR upgrades math-expressions to a version has improved equality checks for tuples and related. The following changes where made:
- tuples, vectors, altVectors, and open intervals are considered identical even deep inside a mathematical expression
- arrays and closed intervals are considered identical even deep inside a mathematical expression
- tuples, vectors, altVectors, and open intervals  are treated as identical when sorting
- arrays and closed intervals are considered identical when sorting.
In addition, the complex numerical answer validation will always be available if `symbolicEquality` is not specified, even if the expression contains operators such as logical or set operators.
Fixes #168
=> improve equality checks involving tuples, vectors, intervals, and arrays

packages/doenetml-worker/src/test/tagSpecific/answer.test.ts, packages/doenetml-worker/src/utils/expandDoenetML.js
Fix a bug where having referencing a `<select>` directly into an `<award>` caused a crash.
=> bugfix: answer with select in award

packages/doenetml-worker/src/components/MathOperators.js, packages/doenetml-worker/src/test/tagSpecific/mathoperators.test.ts
This PR takes the absolute value when calculating `<gcd>` and `<lcm>` so that they don't return negative values when given negative arguments.
Fixes #275.
=> gcd and lcm don't return negative numbers

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml/package.json, packages/doenetml/src/doenetml.tsx, packages/doenetml/src/utils/isVisible.ts, packages/standalone/package.json
This PR changes the initialization of `<DocViewer>` so that it starts off with `hidden=true` and switches to `hidden=false` only when its `<div>` is "visible" somewhere on the current browser page. (It does not have to be in the current browser viewport.) Since the renderers are not initialized until `hidden=false`, this approach allows core to complete its slow initialization even while inside a hidden `<div>` but for jsxgraph to hold off its initialization until the `<div>` is no longer hidden. Since, for some reason, initializing jsxgraph inside a hidden `<div>` can cause garbled output, this algorithm represents a tradeoff that allows core to complete its initialization ahead of time for a hidden document while still producing readable graphs.
=> Prevent initial rendering of DoenetML when it is hidden

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/CoreWorker.js, packages/doenetml-worker/src/Dependencies.js, packages/doenetml-worker/src/test/tagSpecific/sectioning.test.ts, packages/doenetml-worker/src/test/utils/test-core.ts, packages/doenetml/package.json, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/doenetml.tsx, packages/doenetml/src/utils/docUtils.ts, packages/standalone/package.json
This PR adds a `initializeCounters` attribute to `<DoenetViewer>` that allows one to alter the initial value of auto-numbered sectioning components.
=> add the ability to initialize section (and similar) counters

packages/doenetml-iframe/src/iframe-viewer-index.ts, packages/doenetml-iframe/src/index.tsx, packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/test/utils/test-core.ts, packages/doenetml/src/EditorViewer/EditorViewer.tsx, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/Viewer/renderers/codeViewer.jsx, packages/doenetml/src/doenetml.tsx, packages/test-cypress/cypress/e2e/DocViewer/docViewerAttributes.cy.js, packages/test-cypress/src/CypressTest.tsx, packages/test-viewer/src/main.jsx, packages/test-viewer/src/test/testViewer.tsx
This PR adds a few more checks to message event listeners to filter out events that come from the same origin.
It also removes the `allowSaveSubmissions` flag which is obsolete given that we now only support SPLICE messages for saving state, and SPLICE combines saving submissions and state.
=> add more location checks to message listener

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-worker/src/CoreWorker.js, packages/doenetml/package.json, packages/doenetml/src/Viewer/DocViewer.tsx, packages/standalone/package.json
This PR adds activityId and docId to all SPLICE calls, changes the assumption to have parsed state received via SPLICE, and allows messages where either the window or parent locations matches the origin.
=> add activityId and docId to all SPLICE calls

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-iframe/src/iframe-viewer-index.ts, packages/doenetml-iframe/src/index.tsx, packages/doenetml-iframe/src/utils.ts, packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/CoreWorker.js, packages/doenetml/package.json, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/doenetml.tsx, packages/standalone/package.json, packages/test-cypress/cypress/e2e/DocViewer/docViewerAttributes.cy.js, packages/test-cypress/src/CypressTest.tsx
This PR adds new callbacks `reportScoreAndState`,  `documentStructure`, and `initialized` callbacks, and removes the `updateCreditAchieved` callback. It also adds the ability to pass in initial state via the `initialState` prop.
The `reportScoreAndState` callback and `initialState` prop will prevent the corresponding SPLICE messages if they are present.
=> New callbacks

packages/doenetml-iframe/src/iframe-editor-index.ts, packages/doenetml-iframe/src/iframe-viewer-index.ts, packages/doenetml-iframe/src/index.tsx, packages/doenetml-iframe/src/utils.ts, packages/doenetml/src/EditorViewer/EditorViewer.tsx, packages/doenetml/src/doenetml.tsx
This PR adds a `doenetmlChangeCallback` to the editor, which is triggered whenever the viewer inside the editor is updated. The callback returns the variants and the base level component counts.
=> add doenetmlChangeCallback to DoenetEditor

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-worker/src/ComponentTypes.js, packages/doenetml-worker/src/components/PostponeRenderContainer.js, packages/doenetml-worker/src/components/Sectioning.js, packages/doenetml-worker/src/components/Solution.js, packages/doenetml-worker/src/components/abstract/SectioningComponent.js, packages/doenetml-worker/src/test/tagSpecific/sectioning.test.ts, packages/doenetml/package.json, packages/doenetml/src/Viewer/renderers/section.jsx, packages/doenetml/src/Viewer/renderers/solution.jsx, packages/standalone/package.json, packages/test-cypress/cypress/e2e/tagSpecific/sectioning.cy.js
This PR adds a `postponeRendering` attribute to `<aside>` and `<proof>`. Assuming they don't start open, the contents (other than title) are not created until after they are opened. This feature can be used to speed up the initial render of the document if the postponed sections contain content that is slow to create.
For these sections, and for solution which already postponed rendering, immediately open the box when they are clicked open to give visual feedback that they were opened. Then, do the (possibly slow) work of creating the components and rendering them.
=> optionally postpone rendering of collapsible sections

packages/doenetml-worker/src/components/Ref.js, packages/doenetml/src/doenetml.tsx, packages/utils/src/version/doenetMLversion.js
This PR eliminates the feature were saving was disabled when a user is specified. Such saving logic is best left to the app.
It also changes the foreshadowed deprication date of old features to 2025.
=> do not disable saving if user is specified

packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/components/Ref.js, packages/doenetml-worker/src/components/Video.js, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/Viewer/renderers/ref.jsx
Remove obsolete references to `page` that persisted from when DoenetML could represent multi-page documents.
=> remove obsolete references to `page`

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/components/Answer.js, packages/doenetml-worker/src/components/Document.js, packages/doenetml-worker/src/components/Ref.js, packages/doenetml-worker/src/components/Video.js, packages/doenetml-worker/src/test/tagSpecific/document.test.ts, packages/doenetml/package.json, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/Viewer/renderers/ref.jsx, packages/standalone/package.json, packages/test-cypress/cypress/e2e/tagSpecific/codeeditor.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/copy.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/paginator.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/problem.cy.js
DoenetML had this concept of "scored items", which were sectioning components with `aggregateScores` set and any answer blanks not in such a sectioning component. This PR changes their name to "scored components", as the better reflects the concept and facilitates the use of the term "item" to refer the DoenetML document itself when it is part of a problem set.
=> Rename scored items to scored components

packages/doenetml-iframe/src/iframe-editor-index.ts, packages/doenetml-iframe/src/iframe-viewer-index.ts, packages/doenetml/src/EditorViewer/EditorViewer.tsx, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/Viewer/renderers/answer.jsx, packages/doenetml/src/Viewer/renderers/booleanInput.jsx, packages/doenetml/src/Viewer/renderers/choiceInput.jsx, packages/doenetml/src/Viewer/renderers/mathInput.jsx, packages/doenetml/src/Viewer/renderers/matrixInput.jsx, packages/doenetml/src/Viewer/renderers/section.jsx, packages/doenetml/src/Viewer/renderers/textInput.jsx, packages/doenetml/src/Viewer/renderers/utils/AnswerResponseMenu.tsx, packages/doenetml/src/Viewer/useDoenetRenderer.tsx, packages/doenetml/src/doenetml.tsx
The PR adds `showAnswerResponseMenu` and ` answerResponseCounts` attributes to `<DoenetViewer>` and `<DoenetEditor>`. If `showAnswerResponseMenu`  is set to `true`, then we add a button menu after each answer, that gives an option to show responses for that answer.  The text of the button is the number of responses for that answer, as determined by `answerResponseCounts`. If the menu option is selected, then we send a message to the containing app that we are requesting the answer responses to that particular answer.
=> add showAnswerResponseMenu and answerResponseCounts attributes

packages/doenetml-worker/src/Core.js, packages/doenetml-worker/src/CoreWorker.js, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/utils/docUtils.ts
This PR adds the `initializeCounters` object to the state that is loaded/saved. In this way, counters will have the same values regardless of the `initializeCounters` object passed in when a document with saved state is loaded.
=> add initializeCounters to the state that is saved and loaded

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml/package.json, packages/doenetml/src/Viewer/renderers/utils/AnswerResponseMenu.tsx, packages/standalone/package.json
This PR removes the slash in front of answer ids when displaying the answer response menu, just to make the answer id easier to read.
=> remove leading slash from answerId in answer response menu

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml/package.json, packages/doenetml/src/EditorViewer/EditorViewer.tsx, packages/doenetml/src/Viewer/renderers/choiceInput.css, packages/standalone/package.json
This PR adds a `min-height` to choice input containers so that they don't overlap when the DoenetML is embedded in a google site.
It also includes some formatting tweaks for the editor.
=> fix css so choiceinputs are not cramped on google sites

packages/doenetml-worker/src/components/Answer.js, packages/doenetml-worker/src/test/tagSpecific/answer.test.ts
This PR fixes a bug where specifying isResponse on a composite with non-standard case lead to a duplicate prop error
=> Fix bug to handle non-standard case of isResponse in composites

packages/doenetml-iframe/vite.config.ts, packages/doenetml-prototype/vite.config.ts, packages/doenetml-worker-rust/vite.config.ts, packages/doenetml-worker/vite.config.ts, packages/doenetml/vite.config.ts, packages/standalone/vite.config.ts, packages/static-assets/vite.config.ts, packages/test-viewer/vite.config.ts, scripts/vite-plugins.ts
Don't show warnings about using `eval`.
I tried to suppress the output of the big long Base64 URL in the build logs, but couldn't figure out how...
=> Supress a few warnings to make for cleaner build logs

package-lock.json, packages/doenetml/src/Viewer/renderers/list.jsx
This PR fixes a bug that was causing paragraphs in number lists to display on a different line than the number when viewed in Firefox.
The solution was to remove the `<a>` tag used for an anchor inside the `<li>` tags (also from the `<ul>` and `<ol>` tags). These are unnecessary as the "id" attributes in these tags suffice for link targets.
=> remove <a> tags from list renderers

.github/workflows/gh-pages-docs.yml, packages/doenetml-iframe/src/index.tsx, packages/doenetml-worker-javascript/src/Core.js, packages/doenetml-worker-javascript/src/CoreWorker.ts, packages/doenetml-worker-javascript/src/components/Document.js, packages/doenetml-worker-javascript/src/components/Solution.js, packages/doenetml-worker-javascript/src/components/abstract/SectioningComponent.js, packages/doenetml-worker-javascript/src/test/tagSpecific/solution.test.ts, packages/doenetml-worker-javascript/src/test/utils/test-core.ts, packages/doenetml-worker/lib-js-wasm-binding/src/CoreWorker.ts, packages/doenetml/src/Viewer/DocViewer.tsx, packages/doenetml/src/doenetml.tsx
This PR introduces a new `solutionDisplayMode`: "buttonRequirePermission". In this mode, a solution starts off collapsed, identical to "button" mode. However, when a user attempts to open a solution, a "SPLICE.requestSolutionView" message is sent. In order for the solution to open, a matching "SPLICE.requestSolutionView.response" must be received with `{allowView: true}`. Otherwise, the solution remains closed, and the user cannot view the solution.
This mode allows applications to verify and record the fact that a student viewed a solution before the solution will be revealed. A loss of a connection with the server will disallow solution views rather than allowing the solution to be viewed without detecting the fact.
=> request solution view callback when solutionDisplayMode is "buttonRequirePermission"

packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast.test.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast_compactify.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast_compactify.test.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast_merge.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/ref_expand.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/ref_expand.test.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/ref_resolve.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/ref_resolve.test.rs, packages/doenetml-worker/lib-doenetml-core/tests/test_utils/mod.rs, packages/doenetml/src/EditorViewer/EditorViewer.tsx
This PR extends the rust resolver to resolve references in indices of path paths. For example, in a reference `$x.y[$n]`, the `$n` from the index is resolved to its referent.
=> Resolve references in leftover path parts

packages/doenetml-worker-javascript/src/Core.js, packages/doenetml/src/Viewer/useDoenetRenderer.tsx, packages/test-cypress/cypress/e2e/baseComponent/renderCommas.cy.js
This PR fixes a bug where the calculations to add commas to composite replacements did not account for the fact that hidden components and components without renderers were removed from the list of rendered components.
=> Bugfix: account for hidden or components without renderers when adding commas from composites

packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast_compactify.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast_compactify.test.rs
The PR fixes a bug in flat dast compactification, where the indices of unresolved paths were not shifted.
=> Correctly adjust indices when compactifying the flat dast

packages/doenetml-worker/lib-js-wasm-binding/src/CoreWorker.ts, packages/vscode-extension/extension/package.json, packages/vscode-extension/package.json, packages/vscode-extension/src/extension/index.ts, packages/vscode-extension/src/extension/preview-panel/doenet-preview-panel.ts
This PR fixes data-uri nonesense when loading the `.wasm` file for the Rust core so that the vscode extension works.
=> Fix the vscode extension

package-lock.json, packages/docs-nextra/next-env.d.ts, packages/docs-nextra/next.config.mjs, packages/doenetml-iframe/package.json, packages/doenetml/package.json, packages/standalone/package.json
Minifying the docs causes an error because two instances of the minified variable `e` are created. This PR stops minification when building the docs.
After this, the docs should work in Chrome, but they appear not to work in Firefox, with no discernable reason why...
=> Don't minify the docs

packages/doenetml/src/Viewer/useDoenetRenderer.tsx
When using Firefox and selecting a variant from a sequence, the data for the new variant may not populate the Redux store right away. This PR uses default values while the store catches up.
=> Fix race condition when selecting from sequence

.github/workflows/on-pull-request.yml, packages/doenetml/package.json, packages/ui-components/package.json
Use the wireit cache to optimize building in the CI so that tests and build can happen in different jobs.
=> Optimize CI

packages/doenetml-worker-javascript/src/Core.js, packages/doenetml-worker-javascript/src/Dependencies.js, packages/doenetml-worker-javascript/src/components/Collect.js, packages/doenetml-worker-javascript/src/components/Shuffle.js, packages/doenetml-worker-javascript/src/components/Sort.js, packages/doenetml-worker-javascript/src/components/abstract/Copy.js, packages/doenetml-worker-javascript/src/test/copying/extend.test.ts, packages/doenetml-worker-javascript/src/test/tagSpecific/answer.test.ts
This PR removes the `sourceAttributesToIgnore` on the abstract `<_copy>` tag (which is what the `extend` attribute produces) and the `<collect>` tag. The attribute was not widely publicized, and its main purpose was to prevent the `isResponse` attribute from being copied when referencing a component. However, we decided it was an unnecessary complexity and it was better to have consistent rules for all attributes. Now, `isResponse` is copied on references like all attributes (other than the one remaining exception of `labelIsName`).
=> remove the `sourceAttributesToIgnore` attribute and the special case for the `isResponse` attribute

packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast_compactify.rs, packages/doenetml-worker/lib-doenetml-core/src/dast/flat_dast/untagged_flat_dast_compactify.test.rs
This PR fixes a bug in the compactify algorithm that was leading to circular references.
The bug occurred when one had a references inside the index of an extend attribute, as the `$n` in this example.
```
<math extend="$m[$n]" />
```
In these circumstances, the reference `$m` is removed in the compactification but the reference `$n` remains. If this was the only removed element, then `$n` is shifted to take on the former index of `$m`. But, since its parent was `$m` and we didn't shift indices of removed elements, the parent of `$n` ends up being itself, creating a circular reference!
The solution is to shift references to removed indices to their parent.
=> compactify bug fix: handle references in index of extend attribute

packages/doenetml-worker-javascript/src/test/copying/extend_references.test.ts, packages/parser/src/lezer-to-dast/lezer-to-dast-utils.ts, packages/parser/test/pretty-print.test.ts
Fixes #500 
Not the perfect fix, but I think it should handle any user surprise. A zero-width space is inserted after `&dollar;` if converting it to `$` would produce a new ref.
=> Dont convert &dollar; directly to $ if it would create a new macro

package-lock.json, package.json, packages/doenetml-worker-javascript/src/test/math/mathExpressionsEquality.test.ts, packages/doenetml-worker-javascript/src/test/tagSpecific/periodicset.test.ts, packages/doenetml-worker-javascript/src/utils/periodicSetEquality.js
With this PR, the precedence of the `not` operator in `<math>` tags reverts to the behavior from version 0.6, where `not` has a lower precedence than relation operators.
Feedback from users was that they preferred to not have parentheses for expressions such as
```
<boolean>not $x = 3</boolean>
```
Instead, one will need parentheses for logical operations such as if `$A` and `$B` are booleans in the expression:
```
<boolean>($not A)  = $B</boolean>
```
This reverts a change that came in with the upgrade of `math-expressions` to `2.0.0-alpha71` in #249. With upgrading `math-expressions` to `2.0.0-alpha76`, we have reverted to the lower precedence of `not`.
=> decrease precedence of not operator

packages/doenetml-worker-javascript/src/components/abstract/BaseComponent.js, packages/static-assets/scripts/generate-entity-map.ts, packages/static-assets/scripts/get-schema.ts, packages/static-assets/src/generated/doenet-relaxng-schema.json, packages/static-assets/src/generated/doenet-schema.json
The PR adds an `extend` and a `copy` attribute to the base component so they show up in the schema. It also does a little clean up on static assets.
=> Add `extend` and `copy` attributes to schema for all components

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml/package.json, packages/doenetml/src/Viewer/renderers/answer.tsx, packages/doenetml/src/Viewer/renderers/utils/AnswerResponseMenu.tsx, packages/standalone/package.json
This PR changes the answer response menus to use root names, if they exist, rather than component indices to identify the answers. In this way, instructors will see descriptive terms rather than numbers when view student responses.
Fixes #487
=> use root names to identify answers in answer response menu

packages/doenetml-worker-javascript/src/components/MathOperators.js, packages/doenetml-worker-javascript/src/test/tagSpecific/mathoperators.test.ts
This PR adds a "recursiveOperands" type to `<extractMath>` that extracts all operands from a math expressions.
For example, for this DoenetML
```
<math name="m">(a+b)/(c(d+e))</math>
<extractMath name="ops" type="recursiveOperands">$m</extractMath>
```
`ops` will be the list `a,b,c,d,e`.
=> extract recursive operands from math expression

packages/doenetml-worker-javascript/src/Core.js, packages/doenetml/src/Viewer/renderers/section.tsx, packages/test-cypress/cypress/e2e/baseComponent/renderCommas.cy.js, packages/test-cypress/cypress/e2e/tagSpecific/problem.cy.js
Fixes a regression from #512 where commas were not rendering correctly around a repeat when it was directly in the document.
=> fix bug when adding commas around composite replacements

packages/doenetml-prototype/src/renderers/doenet/graph.tsx, packages/doenetml-worker-javascript/src/components/ConstrainToGraph.js, packages/doenetml-worker-javascript/src/components/Curve.js, packages/doenetml-worker-javascript/src/components/Graph.js, packages/doenetml-worker-javascript/src/components/Legend.js, packages/doenetml-worker-javascript/src/components/SubsetOfRealsInput.js, packages/doenetml-worker-javascript/src/components/dynamicalSystems/CobwebPolyline.js, packages/doenetml-worker-javascript/src/test/copying/unlinked copy.test.ts, packages/doenetml-worker-javascript/src/test/tagSpecific/graph.test.ts, packages/doenetml-worker-javascript/src/utils/constraints.js, packages/doenetml/src/Viewer/renderers/booleanInput.tsx, packages/doenetml/src/Viewer/renderers/button.tsx, packages/doenetml/src/Viewer/renderers/curve.tsx, packages/doenetml/src/Viewer/renderers/graph.tsx, packages/doenetml/src/Viewer/renderers/image.tsx, packages/doenetml/src/Viewer/renderers/label.tsx, packages/doenetml/src/Viewer/renderers/legend.tsx, packages/doenetml/src/Viewer/renderers/math.tsx, packages/doenetml/src/Viewer/renderers/number.tsx, packages/doenetml/src/Viewer/renderers/pegboard.tsx, packages/doenetml/src/Viewer/renderers/point.tsx, packages/doenetml/src/Viewer/renderers/text.tsx, packages/doenetml/src/Viewer/renderers/textInput.tsx, packages/doenetml/src/Viewer/renderers/utils/graph.ts, packages/doenetml/src/Viewer/renderers/utils/offGraphIndicators.ts, packages/static-assets/src/generated/doenet-relaxng-schema.json, packages/static-assets/src/generated/doenet-schema.json
This PR normalizes the capitalization of graph limits to `xMin`, `xMax`, `yMin`, and `yMax` so that the JS core matches the conventions of the rust core.
=> Normalize capitalization of graph limits

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml/package.json, packages/doenetml/src/EditorViewer/EditorViewer.tsx, packages/doenetml/src/EditorViewer/editor-viewer.css, packages/standalone/package.json
This PR removes the `v06-to-v07` syntax updater from the editor in the `doenetml` package. This way, the package size won't be quite so large. We'll package the syntax updater as a separate package that can be loaded by an app.
=> Remove update syntax converter from editor

packages/doenetml-worker-rust/lib-doenetml-core/src/dast/ref_resolve/build_resolver.rs, packages/doenetml-worker-rust/lib-doenetml-core/src/dast/ref_resolve/resolve.test.rs
This PR changes how ref resolutions work when a parent has the same name as one or more descendants. With this PR, the parent name supersedes the descendants. From outside the parent, references to the shared name are no longer ambiguous but resolve to the parent.
For example, given this DoenetML
```
<a name="x"><b name="x" /></a>
$x
$x.x
```
the reference `$x` now uniquely resolves to `<a>` rather than being ambiguous. By extension, the reference `$x.x` now uniquely resolves to `<b>`.
This change makes the ref resolution behave in a more natural way, as `<a>` is "closer" to the references.
=> parent name supersedes descendants if ref resolutions

packages/doenetml-worker-javascript/src/components/ConditionalContent.js, packages/doenetml-worker-javascript/src/test/tagSpecific/answer.test.ts
This PR reimplements an optimization from DoenetML version 0.6. If a `<conditionalContent>` has a single `<case>` (or zero cases, for which a single `<case>` is sugared in), then don't recreate the replacements when the single condition switches being satisfied. Instead, withhold the replacements when the condition is not satisfied and stop withholding them when the condition is again satisfied.
=> don't recreate replacements for conditional content with one case

packages/doenetml-worker-javascript/src/Core.js, packages/doenetml-worker-javascript/src/components/PostponeRenderContainer.js, packages/doenetml-worker-javascript/src/components/abstract/Copy.js
This PR adds protection when calling functions that create serialized replacements of composite components to make sure that components were not created by other functions during the process. If they were, it's possible two components could have been assigned the same component index.
=> verify no components got added while calculating replacements

packages/doenetml-worker-javascript/src/components/Answer.js, packages/doenetml-worker-javascript/src/components/ChoiceInput.js, packages/doenetml-worker-javascript/src/test/tagSpecific/answer.test.ts, packages/doenetml-worker-javascript/src/test/tagSpecific/choiceinput.test.ts
This PR adds a `preserveLastChoice` attribute to `<choiceInput>`. It has no effect unless the `shuffleOrder` attribute is specified, in which case all the choices are shuffled except for the last one.
Resolves #467.
=> preserveLastChoice option for choice input

packages/doenetml-worker-javascript/src/components/Document.js, packages/doenetml-worker-javascript/src/components/abstract/SectioningComponent.js, packages/doenetml-worker-javascript/src/test/tagSpecific/problem.test.ts, packages/doenetml/src/EditorViewer/EditorViewer.tsx
This PR adds a `showCorrectness` attribute to `<document>` and sectioning components. It has an effect only if `documentWideCheckWork` or `sectionWideCheckWork` is set. Then, if `showCorrectness` is set to `false`, the document-wide/section-wide check work button does not indicate if the submitted answer is correct.
Fixes #465.
=> showCorrectness attribute on section and document

packages/doenetml/src/state/slices/main.ts
This PR checks to make sure a loaded renderer state is defined when attempting to update the renderer state.
It could be undefined in an edge case where an app is causing core to be recreated.
=> Add protection in case load undefined renderer state

package-lock.json, packages/doenetml-iframe/package.json, packages/doenetml-iframe/vite.config.ts, packages/doenetml/package.json, packages/standalone/package.json, packages/v06-to-v07/package.json
This PR simply renames the exported style file of `doenetml-iframe` to be `style.css`.
=> rename iframe style file

packages/doenetml-worker-javascript/src/components/PiecewiseFunction.js, packages/doenetml-worker-javascript/src/test/tagSpecific/piecewisefunction.test.ts
This PR addresses a bug where the `latex` state variable of a piecewise function was not marked `forRenderer`. This meant that a `<piecewiseFunction>` that wasn't inside a component like `<m>` was rendered as `undefined`.
=> bugfix: mark latex of piecewise function as forRenderer

packages/doenetml-worker-rust/lib-doenetml-core/src/utils/parse_json.rs, packages/doenetml/src/EditorViewer/EditorViewer.tsx
The PR fixes a bug where, if one changes the variant via the editor's variant selector too quickly, then an infinite loop oscillating between two variants could be induced. The infinite loop is prevented by setting the `variants` state variable only if changed when receiving the generated variant from the Doenet viewer.
=> Editor sets variants state variable only if changed

packages/doenetml-worker-javascript/src/components/Graph.js, packages/doenetml-worker-javascript/src/test/tagSpecific/graph.test.ts, packages/doenetml/src/Viewer/renderers/graph.tsx, packages/test-cypress/cypress/e2e/tagSpecific/graph.cy.js
The PR fixes a few issues with graphs.
1. Fixes a bug where a graph crashes when navigation buttons are removed.
2. Fixes glitch when panning/zooming a fixed graph.
3. The zoom/pan settings change dynamically with the `fixAxes` state variable.
Fixes #592
=> graph fixes

packages/docs-nextra/pages/tutorials/intermediateTutorial/iT2-1-cartesian.mdx, packages/docs-nextra/pages/tutorials/intermediateTutorial/iT2-2-points.mdx, packages/docs-nextra/pages/tutorials/intermediateTutorial/iT2-3-lines.mdx, packages/docs-nextra/pages/tutorials/intermediateTutorial/iT2-4-properties.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-1-writing-mathematics.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-10-advice.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-3-variables-numbers.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-4-comparison-math.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-5-setup-blocks.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-6-user-input.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-7-functions.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-8-domains.mdx, packages/docs-nextra/pages/tutorials/introdTutorial/iT1-9-sliders.mdx, packages/docs-nextra/theme.config.tsx
This PR converts the introductory and intermediate tutorials to the conventions of version 0.7 and the embedded doenet editor in nextra.
The section "A Comparison of Mathematics Tags" still needs some conversions, as the `<m>` tag no longer works exactly as described.
=> convert tutorials to 0.7

packages/doenetml-worker-javascript/src/components/abstract/Input.js, packages/doenetml/src/utils/checkWork.tsx, packages/test-cypress/cypress/e2e/tagSpecific/answer.cy.js
This PR makes check work buttons accessible by adding aria-labels that explain their function. It also changes the answer messages to be spans rather than buttons, as they don't have an action.
Fixes #597
=> add aria labels to check work buttons
